increasing the error margin in response to the flaky test that causes this error:
unexpected build status; build log was: ------ Legacy code started this job.  No cause information is available Recording test results Test reports were found but none of them are new. Did tests run?  For example, /tmp/hudson3604989730528561398test/jobs/test0/workspace/junit.xml is 1 sec old  Finished: FAILURE  ------  expected:<UNSTABLE> but was:<FAILURE>

Stacktrace

junit.framework.AssertionFailedError: unexpected build status; build log was:
------
Legacy code started this job.  No cause information is available
Recording test results
Test reports were found but none of them are new. Did tests run? 
For example, /tmp/hudson3604989730528561398test/jobs/test0/workspace/junit.xml is 1 sec old
Finished: FAILURE
------
 expected:<UNSTABLE> but was:<FAILURE>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:282)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at org.jvnet.hudson.test.HudsonTestCase.assertBuildStatus(HudsonTestCase.java:520)
	at hudson.tasks.junit.CaseResultTest.testIssue20090516(CaseResultTest.java:74)

Standard Output

=== Starting testIssue20090516

Standard Error

2009-07-20 07:20:23.430::INFO:  jetty-6.1.11
2009-07-20 07:20:23.434::INFO:  NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
2009-07-20 07:20:23.436::INFO:  Started SocketConnector@0.0.0.0:45218