Merged revisions 8773-8785 via svnmerge from https://hudson.dev.java.net/svn/hudson/trunk/hudson
........
  r8774 | k2nakamura | 2008-04-20 07:58:57 +0200 (zo, 20 apr 2008) | 1 line
  
  added svn-tag plugin.
........
  r8775 | jglick | 2008-04-21 17:05:55 +0200 (ma, 21 apr 2008) | 1 line
  
  Fixing NPE verifying Hudson instance.
........
  r8776 | jglick | 2008-04-21 18:49:59 +0200 (ma, 21 apr 2008) | 2 lines
  
  Fixing project metadata broken by kohsuke in 8770 for no obvious reason.
........
  r8777 | jglick | 2008-04-21 18:54:29 +0200 (ma, 21 apr 2008) | 2 lines
  
  Fixing POM reference.
........
  r8778 | jglick | 2008-04-21 19:26:21 +0200 (ma, 21 apr 2008) | 5 lines
  
  testng 5.7 plugin appears broken, downgrading to 5.1.
  org.apache.maven.surefire.booter.SurefireExecutionException: org.testng.xml.XmlSuite.setParallel(Z)V; nested exception is java.lang.NoSuchMethodError: org.testng.xml.XmlSuite.setParallel(Z)V
  java.lang.NoSuchMethodError: org.testng.xml.XmlSuite.setParallel(Z)V
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:123)
  	at org.apache.maven.surefire.Surefire.run(Surefire.java:132)
........
  r8779 | peterkittreilly | 2008-04-22 00:36:47 +0200 (di, 22 apr 2008) | 1 line
  
  disable M2 for the moment
........
  r8780 | mdonohue | 2008-04-22 03:51:55 +0200 (di, 22 apr 2008) | 3 lines
  
  Add help popouts to the bitkeeper configuration options, rather than using the
  description subtext.
........
  r8781 | redsolo | 2008-04-22 09:00:48 +0200 (di, 22 apr 2008) | 1 line
  
  [maven-release-plugin] prepare release violations-0.5.8
........
  r8783 | redsolo | 2008-04-22 09:01:17 +0200 (di, 22 apr 2008) | 1 line
  
  [maven-release-plugin] prepare for next development iteration
........
  r8784 | bagrehc | 2008-04-22 14:19:12 +0200 (di, 22 apr 2008) | 1 line
  
  Translated to portuguese-brazil.
........
  r8785 | bagrehc | 2008-04-22 20:28:23 +0200 (di, 22 apr 2008) | 1 line
  
  Translated to portuguese-brazil.
........