Removed Guice DI due to a java.lang.NoClassDefFoundError: com/google/inject/internal/Finalizer$ShutDown thrown when the DTKIT library is used by a Hudson plugin as the xUnit Hudson plugin